on:
  push:
    branches:
      - main

name: Build, Release New Apk

jobs:
  build:
    name: Build and Release new apk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '13.0.2'
          cache: 'gradle'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.10.6"
          channel: 'stable'
          cache: true
      - run: flutter pub get
      - run: flutter build apk --release --split-per-abi

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*"
          tag: 1.0.${github.run_number}
          # token: ${{ secrets.TOKEN }}
